---
- name: Prepare undercloud
  gather_facts: false
  hosts: undercloud
  tags: pull
  tasks:
    - include_tasks: tasks/prepare.yml

- name: Extract Ceph data from DCN servers
  gather_facts: false
  hosts: dcn0-distributedcomputehci-0 #dcn1-distributedcomputehci-0
  become: true
  tags: pull
  tasks:
    - include_tasks: tasks/make_client.yml
      vars:
        dcn: "{{ item.dcn }}"
        host: "{{ item.host }}"
      loop:
        - { dcn: 'dcn0', host: 'dcn0-distributedcomputehci-0' }
        #- { dcn: 'dcn1', host: 'dcn1-distributedcomputehci-0' }
        
- name: Configure central control plane as DCN Ceph cluster client
  gather_facts: false
  become: true
  hosts: control-plane-controller-0
  tags: push
  tasks:
    - include_tasks: tasks/install_client.yml
      vars:
        dcn: "{{ item }}"
      loop:
        - dcn0
        #- dcn1

- name: Configure central control plane with extra glance backends
  gather_facts: false
  become: true
  hosts: control-plane-controller-0
  tags:
    - glance
    - glance_backends
  tasks:
    - include_tasks: tasks/glance_backends.yml
      vars:
        glance_conf: "/var/lib/config-data/puppet-generated/glance_api/etc/glance/glance-api.conf"
        rc: /home/heat-admin/control-planerc
        dcns:
          - dcn0
          #- dcn1

- name: Configure all glance services with experimental feature
  gather_facts: false
  become: true
  hosts: control-plane-controller-0 dcn0-distributedcomputehci-0 #dcn1-distributedcomputehci-0
  tags:
    - glance
    - glance_features
  tasks:
    - include_tasks: tasks/glance_features.yml
      vars:
        import_multi_stores: False
        copy_existing_image: True
        force_container: True
        glance_container_url: 192.168.24.1:8787/tripleomaster/centos-binary-glance-api
        glance_conf: "/var/lib/config-data/puppet-generated/glance_api/etc/glance/glance-api.conf"
