---
- name: Create dcn_ceph_data directory if it does not exist
  file:
    path: dcn_ceph_data
    state: directory
    mode: '0755'

- name: Copy control-planerc into dcn_ceph_data
  copy:
    src: ../control-plane/control-planerc
    dest: dcn_ceph_data/control-planerc
    owner: stack
    group: stack
    mode: '0600'

