---
- name: Prepare undercloud
  gather_facts: false
  hosts: undercloud
  tags: pull
  tasks:
    - include_tasks: tasks/prepare.yml

- name: Extract keyring and config from all Ceph clusters
  gather_facts: false
  hosts: control-plane-controller-0 dcn0-distributedcomputehci-0 #dcn1-distributedcomputehci-0
  become: true
  tags: pull
  tasks:
    - include_tasks: tasks/make_client.yml
      vars:
        ceph_cluster_name: "{{ item.ceph_cluster_name }}"
        ceph_cluster_host: "{{ item.ceph_cluster_host }}"
      loop:
        - { ceph_cluster_name: 'dcn0', ceph_cluster_host: 'dcn0-distributedcomputehci-0' }
        #- { ceph_cluster_name: 'dcn1', ceph_cluster_host: 'dcn1-distributedcomputehci-0' }
        - { ceph_cluster_name: 'central', ceph_cluster_host: 'control-plane-controller-0' }

- name: Configure all Ceph clients
  gather_facts: false
  become: true
  hosts: control-plane-controller-0 dcn0-distributedcomputehci-0 #dcn1-distributedcomputehci-0
  tags: push
  tasks:
    - include_tasks: tasks/install_client.yml
      vars:
        ceph_cluster_name: "{{ item.ceph_cluster_name }}"
        ceph_cluster_host: "{{ item.ceph_cluster_host }}"
      loop:
        - { ceph_cluster_name: 'dcn0', ceph_cluster_host: 'dcn0-distributedcomputehci-0' }
        - { ceph_cluster_name: 'central', ceph_cluster_host: 'control-plane-controller-0' }
        #- { ceph_cluster_name: 'dcn1', ceph_cluster_host: 'dcn1-distributedcomputehci-0' }

- name: Configure glance with backends
  gather_facts: false
  become: true
  hosts: control-plane-controller-0 dcn0-distributedcomputehci-0 #dcn1-distributedcomputehci-0
  tags:
    - glance
    - glance_backends
  tasks:
    - include_tasks: tasks/glance_backends.yml
      vars:
        glance_conf: "/var/lib/config-data/puppet-generated/glance_api/etc/glance/glance-api.conf"
        rc: /home/heat-admin/control-planerc
        dcn_list:
          - dcn0
          # - dcn1

- name: Configure all glance services with experimental feature
  gather_facts: false
  become: true
  hosts: control-plane-controller-0 dcn0-distributedcomputehci-0 #dcn1-distributedcomputehci-0
  tags:
    - glance
    - glance_features
  tasks:
    - include_tasks: tasks/glance_features.yml
      vars:
        import_multi_stores: True
        copy_existing_image: False
        force_container: True
        glance_container_url: 192.168.24.1:8787/tripleomaster/centos-binary-glance-api
        random_tag: "{{ lookup('file', '../patch_glance/RAND') }}"
        glance_conf: "/var/lib/config-data/puppet-generated/glance_api/etc/glance/glance-api.conf"

- name: Configure all nova-computes to use their local glance
  gather_facts: false
  become: true
  hosts: dcn0-distributedcomputehci-0 #dcn1-distributedcomputehci-0
  tags:
    - nova
  tasks:
    - include_tasks: tasks/nova_glance.yml
      vars:
        nova_conf: "/var/lib/config-data/puppet-generated/nova_libvirt/etc/nova/nova.conf"
