---
# dcns variable should only contain the current host
# unless inventory_hostname is control-plane-controller-0
- name: Set dcns list for non-control-plane glance
  set_fact:
    dcns: # rely on convention
      - "{{ inventory_hostname.split('-')[0] }}"
  when:
    - inventory_hostname != "control-plane-controller-0"

- name: Set dcns list for control-plane glance
  # just using dcn_list doesn't work because of how include_tasks works
  set_fact:
    dcns: "{{ dcn_list }}"
  when:
    - inventory_hostname == "control-plane-controller-0"

- name: State what is about to happen
  debug:
    msg: "Configure {{ inventory_hostname }} to use central and {{ dcns }} "

- name: add enabled_backends to DEFAULT section
  ini_file:
    path: "{{ glance_conf }}"
    section: DEFAULT
    option: enabled_backends
    value: "central:rbd, {{ dcns|join(':rbd, ') }}:rbd"

- name: remove registry_host from DEFAULT section
  ini_file:
    path: "{{ glance_conf }}"
    section: DEFAULT
    option: registry_host
    state: absent

- name: remove entire glance_store section
  ini_file:
    path: "{{ glance_conf }}"
    section: glance_store
    state: absent

- name: Set default_backend and central central_rbd_store_user
  set_fact:
    default_backend: central
    central_rbd_store_user: openstack # central uses default key from initial install
  when: inventory_hostname == "control-plane-controller-0"

- name: Set default_backend and central_rbd_store_user for dcn hosts based on hostname
  set_fact:
    default_backend: "{{ inventory_hostname.split('-')[0] }}"
    central_rbd_store_user: central.glance # from ceph cluster name of make_client.yml
  when: inventory_hostname is regex("^dcn[0-9]+")

- name: Add new glance_store and central sections
  blockinfile:
    path: "{{ glance_conf }}"
    block: |
      [glance_store]
      stores=http,rbd
      os_region_name=regionOne
      default_backend = {{ default_backend }}
      [central]
      store_description = "central RBD backend"
      rbd_store_pool = images
      rbd_store_user = {{ central_rbd_store_user }}
      rbd_store_ceph_conf = /etc/ceph/central.conf

- name: Add new DCN sections for central node
  blockinfile:
    path: "{{ glance_conf }}"
    block: |
      [{{ item }}]
      store_description = "{{ item }} RBD backend"
      rbd_store_pool = images
      rbd_store_user = {{ item }}.glance
      rbd_store_ceph_conf = /etc/ceph/{{ item }}.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  loop: "{{ dcns }}"
  when:
    - inventory_hostname == "control-plane-controller-0"

- name: Add DCN section for the DCN node
  blockinfile:
    path: "{{ glance_conf }}"
    block: |
      [{{ item }}]
      store_description = "{{ item }} RBD backend"
      rbd_store_pool = images
      rbd_store_user = openstack
      rbd_store_ceph_conf = /etc/ceph/{{ item }}.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  loop: "{{ dcns }}"
  when:
    - inventory_hostname is regex("^dcn[0-9]+")

- name: restart glance container
  shell: "systemctl restart tripleo_glance_api.service"

- when:
    - inventory_hostname == "control-plane-controller-0"
  block:
    - name: query central glance stores-info
      shell: "source {{ rc }}; glance stores-info"
      register: stores_info

    - name: show stores_info
      debug:
        msg: "{{ stores_info.stdout_lines }}"
