---
- when:
    - ceph_cluster_host == inventory_hostname
  block:
    - name: download ceph configuration file
      synchronize:
        mode: pull
        src: "/etc/ceph/{{ ceph_cluster_name }}.conf"
        dest: "dcn_ceph_data/{{ ceph_cluster_name }}.conf"

    - name: set ceph command fact
      set_fact:
        ceph: "podman exec ceph-mon-{{ ceph_cluster_host }} ceph --conf /etc/ceph/{{ ceph_cluster_name }}.conf"

    - name: set ceph keyring fact
      set_fact:
        keyfile: "/etc/ceph/client.{{ ceph_cluster_name }}.glance.keyring"

    - name: create ceph client glance keyring
      shell: "{{ ceph }} auth get-or-create client.{{ ceph_cluster_name }}.glance mon 'profile rbd' osd 'profile rbd pool=images'"

    - name: export ceph client glance keyring to file
      shell: "{{ ceph }} auth get client.{{ ceph_cluster_name }}.glance > {{ keyfile }}"

    - name: download ceph client glance keyrings
      synchronize:
        mode: pull
        src: "{{ keyfile }}"
        dest: "dcn_ceph_data/client.{{ ceph_cluster_name }}.glance.keyring"

